### ISSUE TITLE
Commenting

### ISSUE THREAD

**Issue by chrisballinger** [guardianproject/securereader_ios#10]
- [x] Reading comments
  - [x] Add paik, wfw, slash namespaces to SCRItem (commentCount, paikId, commentsURL)
  - [x] Fetch comments from commentsURL
  - [x] SCRCommentItem subclass of SCRItem with different yapCollection
  - [x] Add way to fetch array of SCRCommentItem to SCRItem
  - [x] UI for Global comments feed?
  - [x] Only show comments UI on SCRItems with non-nil commentsURL
- [x] Posting comments
  - [x] SCRWordpressClient support
- [x] Ensure comment data is fetched over Tor if desired
- [x] Create Nickname screen

**Comment by davidchiles** [comment]
@chrisballinger  Whenever I use [getCommentCountsForPostId:](https://github.com/guardianproject/securereader_ios/blob/dacb562a2a87db0c8922166dd1b660f145b0f93e/SecureReader/Views/SCRWordpressClient.h#L51) I get `approvedCount = 17`. Am I doing something wrong [here](https://github.com/guardianproject/securereader_ios/commit/ba87bd30ee56b0a2642c96a7164adc8bd7908ffb#diff-ce6f549c2b1406c8e04de75f6608c5faR98).

**Comment by chrisballinger** [comment]
@davidchiles That's the count for postId 1 so it must not be passing the postId parameter properly. I have an idea of what's wrong, I'll push a fix in a minute.

**Comment by chrisballinger** [comment]
Looks like this is complete
