### ISSUE TITLE
Post new Stories to server

### ISSUE THREAD

**Issue by chrisballinger** [guardianproject/securereader_ios#11]
- [x] Blocking on server side support? @vanevery 
- [x] Implement using [wpxmlrpc](https://github.com/wordpress-mobile/wpxmlrpc) library?
- [x] Image posting support

**Comment by chrisballinger** [comment]
Even better: https://github.com/wordpress-mobile/WordPress-API-iOS

edit: actually that library sucks

**Comment by chrisballinger** [comment]
Added SCRWordpressClient in 3548fdeb3184b3f23f59eb4c308b9ad1ec92513b. It only supports text posts, no images. There are tests that pass and the results end up on the server.

**Comment by N-Pex** [comment]
@chrisballinger @davidchiles Low-ish priority: it would be great if one of you could have a look at the deleteMediaButtonClicked method in SCRAddPostViewController.m. I am having a hard time removing a media item correctly (maybe it has something to do with the way it is added in imagePickerController:didFinishPickingMediaWithInfo:)

Try the following:
1. Go to add new post screen
2. Click the image placeholder and add an image from gallery or camera
3. Click the delete button to remove the image again
Result: it is not removed. The call chain trickles down to enumerateMediaItemsInTransaction:block: being called from setItem: in SCRMediaCollectionView.m. Unexpectedly this returns 1 item, not 0.

**Comment by chrisballinger** [comment]
I'm going to close this issue, but I'm not sure if the last comment was addressed.

@N-Pex Should we make a new issue for https://github.com/guardianproject/securereader_ios/issues/11#issuecomment-116758962?
