### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by chrisballinger** [guardianproject/securereader_ios#13]
http://invis.io/KU25WKCCX
- [x] Language setup
- [x] Tor setup
- [x] Feed curation
- [x] TouchID / PIN setup #16 
- [x] Settings screen overlay / tips (minimize data use, panic feature)

**Comment by N-Pex** [comment]
We need to figure out what to do with the feed curation step. Somehow the default opml should be piped through this, and only the ones we select will later be added.

**Comment by davidchiles** [comment]
The easy answer is to just set the database passphrase before we show the feed curation. That way we don't have to come up with another way to pass through the feeds.

Language → Tor → TouchID / Pin → Feed curation → Overlay

**Comment by N-Pex** [comment]
Yes, that makes sense. The only negative thing I see with this is that we may download stuff that you will not need, if you decide the deselect a "default subscribed" feed (cause I guess some of them are going to be preselected?)

**Comment by chrisballinger** [comment]
Couldn't we defer all downloads / subscriptions until after the feed
selection step?
