### ISSUE TITLE
SCRItemViewController toolbar items

### ISSUE THREAD

**Issue by chrisballinger** [guardianproject/securereader_ios#17]
@N-Pex Currently the toolbar items are bunched together at the bottom because of the commenting button. Could you space them out a bit and hook up a stub action method to the share icon? I am having trouble hooking it up because the storyboard just shows a bunch of blank space in the toolbar area so it's hard to see what I'm modifying.

Thank you!

![ios simulator screen shot may 21 2015 5 47 18 pm](https://cloud.githubusercontent.com/assets/518687/7761943/88afddf4-ffe1-11e4-9c78-8731f8a66c51.png)

**Comment by N-Pex** [comment]
@chrisballinger Oops, sorry, work in progress =) Fixed now. The stub is in SCRItemViewController.

**Comment by chrisballinger** [comment]
@N-Pex Thank you!
