### ISSUE TITLE
Make sure all strings are localizable

### ISSUE THREAD

**Issue by chrisballinger** [guardianproject/securereader_ios#21]

**Comment by N-Pex** [comment]
There's a script called "update_strings.sh" in the /scripts folder that will run genstrings on the project, then update the localizable .strings files with only the updated strings (not overwriting what's already there).

**Comment by chrisballinger** [comment]
Some strings in storyboard aren't making it over, should check on that

**Comment by N-Pex** [comment]
Which strings, what operation are you trying to do?

I just tried it on Swedish, seems to work. First running the script above, then doing SecureReader->Editor->Export for Localization... (like this: https://developer.apple.com/library/ios/documentation/MacOSX/Conceptual/BPInternational/LocalizingYourApp/LocalizingYourApp.html)

**Comment by N-Pex** [comment]
Ok, storyboard strings files are not updated by XCode. I built a script for this, now also in the scripts folder.
