### ISSUE TITLE
View media full screen

### ISSUE THREAD

**Issue by N-Pex** [guardianproject/securereader_ios#23]
Play video and show images full screen (zoomable) when clicking on them in the item view. This is present in the Android version, should be in iOS as well?

**Comment by davidchiles** [comment]
There are two pods that look promising [JTSImageViewController](https://github.com/jaredsinclair/JTSImageViewController) & [NYTPhotoViewer](https://github.com/NYTimes/NYTPhotoViewer). I'm going to try JTSImageViewController first.
