### ISSUE TITLE
I get locked out of the app, when I don't set a password.

### ISSUE THREAD

**Issue by cstiens** [guardianproject/securereader_ios#26]
In the onboarding setup, I don't set a password. But, when I close the app and come back to it later, it prompts me to enter a password.

**Comment by N-Pex** [comment]
Happens to me as well. Start app, press home button to go back to home screen, tap the app icon to open it up again. Lock screen is shown.

**Comment by chrisballinger** [comment]
Fixed in https://github.com/guardianproject/securereader_ios/commit/1163e2f0f28d02748ff0597743226001f9057ade
