### ISSUE TITLE
Feeds I subscribed to during onboarding don't show in 'Following' tab of the Feeds View

### ISSUE THREAD

**Issue by cstiens** [guardianproject/securereader_ios#27]
I subscribed to feeds during the on boarding process, but when I select the feeds tab, no feeds are listed under 'Following'. The latest stories are shown in the News view, however.

**Comment by chrisballinger** [comment]
@N-Pex I'm still seeing this issue on latest master branch. I think the problem is that they're not being saved to Yap properly after the onboarding step. Or perhaps there's another issue with that Yap view itself.

**Comment by N-Pex** [comment]
@chrisballinger Ok, checked in another fix, removing old ugly code to handle yapKey discrepancy fixes because of xmlUrl and actual url used. Could you please try again?

**Comment by chrisballinger** [comment]
:+1: :+1: :+1:
