### ISSUE TITLE
App Icon is low resolution

### ISSUE THREAD

**Issue by chrisballinger** [guardianproject/securereader_ios#28]
@cstiens Apple may flag the app for resizing the app icon up from a smaller size. We need a full 1024x1024 render of the app icon as a transparent PNG without rounded corners. Thank you!

**Comment by N-Pex** [comment]
Turns out InkScape was able to do a smooth resize of the SVG:

![paik_launcher_large](https://cloud.githubusercontent.com/assets/5418622/8800625/ac9c3c28-2fb4-11e5-89b5-e777cf60ea64.png)

**Comment by chrisballinger** [comment]
Looks great, thanks!

**Comment by cstiens** [comment]
I noticed and imperfection in the graphic so I am attaching an updated version. Please implement.
![ios_launcher_1024x1024](https://cloud.githubusercontent.com/assets/1434597/9065129/808faf66-3a95-11e5-814d-1aa30ccfc141.png)
