### ISSUE TITLE
Support video and audio media items

### ISSUE THREAD

**Issue by davidchiles** [guardianproject/securereader_ios#29]
We currently download these media items but have no way of playing them.
Todo:
- [x] Thumbnails for video
- [x] Thumbnail for audio (have assets now)
- [x] Playback video
- [x] Playback audio

**Comment by chrisballinger** [comment]
Have you found any good example feeds that include this kind of content? I guess maybe some good podcast feeds?

**Comment by davidchiles** [comment]
Yeah there are nasa podcast feeds: https://www.nasa.gov/content/nasa-rss-feeds

**Comment by DavidMOliver** [comment]
Here's the NASA podcasts feed

http://www.nasa.gov/rss/dyn/NASAcast_vodcast.rss

David Oliver, Program Manager

David M. Oliver | david@olivercoady.com | http://olivercoady.com |
http://dmo.tel | Ostel: oliv | +1 970 368 2366
