### ISSUE TITLE
Feed refresh activity spinner freezes

### ISSUE THREAD

**Issue by chrisballinger** [guardianproject/securereader_ios#31]
Not sure why this happens but I think it's related to a KVO problem. A quick fix would be pulling down to refresh should reset the state of the spinner.

**Comment by chrisballinger** [comment]
I'm still seeing this on the latest builds where sometimes instead of freezing it just spins forever.

**Comment by N-Pex** [comment]
@davidchiles I've tracked this down to why it happens, but I'll leave it to you to fix, ok? =)

Some feeds, among those the "aftonbladet.se" feed that we have in the default feeds, parse with 0 items.We reach line 155 in SCRFeedFetcher.m, but the feed object is nil so we never enter the block there -> the completion block is never called. Thus the group in refreshSubscribedFeedsWithCompletionQueue is never left, so the "isRefreshing" property is never reset to NO.

**Comment by chrisballinger** [comment]
Aha! Good sleuthing work!
