### ISSUE TITLE
Offline Readability support

### ISSUE THREAD

**Issue by chrisballinger** [guardianproject/securereader_ios#4]
Even better than simple WebView support! The ability to parse the main body of an article and optimize the presentation for mobile devices would also allow for a better UX for Tor users who cannot use regular WebViews safely.

Apparently there is an offline library [DZReadability](https://github.com/DZamataev/DZReadability) that can output mobile-optimized HTML that may be safe enough to render in an offline WebView. RSS feeds that are mainly just headlines with very little content (such as CNN) could be fetched over Tor, processed locally, and then displayed offline at a later time (or shared with others).

**Comment by n8fr8** [comment]
Plus 10! I also see no ethical issue with this since we are scraping at
the client and not the server,.and doing so to assist the user and not
avoid ads, etc.

**Comment by davidchiles** [comment]
Todo:
- [x] Ability to view real website if not using Tor
- [x] Delete cached html when an item is deleted

Decided to UITextView instead since UIWebView cannot be a subview of UIScrollView.
