### ISSUE TITLE
Uploading images when creating a post

### ISSUE THREAD

**Issue by cstiens** [guardianproject/securereader_ios#41]
After I upload an image (from library or camera), I cannot see the image until I upload a second image.  

After uploading a second image, I can only see the first image I uploaded. There is no indication that I uploaded a second image (swipe feature between images doesn't show).

If I go back to my drafts and click on it, I can now see that there are multiple images (swipe feature shows).

**Comment by N-Pex** [comment]
Fixed by 28a30f95260ac0373bd5c488f11018f0649605bd
