### ISSUE TITLE
Image hover menu

### ISSUE THREAD

**Issue by cstiens** [guardianproject/securereader_ios#42]
The "add more photos," "replace," and "delete" buttons work. 

However, when I click delete the image doesn't appear to get deleted. If I go back to drafts and click on the post, the image now shows deleted.

If I add more photos, the new photo will not display.  If I go back to drafts and come back, the new image appears. The same thing happens when I choose to replace a photo.

To "view" I can click on the image itself but not the button.

To swipe between mutliple images I have uploaded. I have to tap on the photo to make the hover menu appear.  I can only swipe between them while this hover menu is apparent.

If I try to post, I get the error message that images are uploading.

**Comment by N-Pex** [comment]
Fixed by d4887bcb0a324855e768c00651aafd994a452fd4
