### ISSUE TITLE
Some feeds give the option to comment

### ISSUE THREAD

**Issue by cstiens** [guardianproject/securereader_ios#45]
Ars Technica, Grantland and Food Network are all doing this. Others may be also -- I have not checked every single feed. If I tap on comment, it takes me to Paik Talk.

Commenting should only be available for feeds within the Paik Persian News.

**Comment by N-Pex** [comment]
Fixed in 31070fe05383414fa77c57a22524e529f175e03b. Added the same mechanism of checking feed URL as in Android version.
