### ISSUE TITLE
Feed search bar is black

### ISSUE THREAD

**Issue by cstiens** [guardianproject/securereader_ios#46]
![img_0162](https://cloud.githubusercontent.com/assets/1434597/9317457/4fe89fe6-4501-11e5-9dba-5ad5baa502fb.PNG)

The feed search is still working, but as a user, I can't see what I'm typing.

**Comment by N-Pex** [comment]
Tint issue after setting bar appearance tint (tor setting toggled). Fixed in e5396c55121647469a6dc3d2009b91e64d1cc8be.
