### ISSUE TITLE
Paik Persian News ("Social Reporter") does not appear in feed list or Following

### ISSUE THREAD

**Issue by DavidMOliver** [guardianproject/securereader_ios#52]
I don't see that Paik Persian News feed in my feed list or in "following".  Therefore, while I can post, I can not see what I, or others, have posted.

The newest builtin_US.opml and builtin_cat_US.opml contain this feed among the list entries.

**Comment by chrisballinger** [comment]
This may have been fixed in https://github.com/guardianproject/securereader_ios/commit/3abd60fff154953324dbf79a31e5c3f51e7c065d

**Comment by N-Pex** [comment]
Yes, fixed.
Den 20 aug 2015 23:33 skrev "Chris Ballinger" notifications@github.com:
