### ISSUE TITLE
Favicon support

### ISSUE THREAD

**Issue by chrisballinger** [guardianproject/securereader_ios#6]
Integrate favicons into the feed list
- [x] Fetching icons 1f111ab422727f2a7bed7ee416d7cb21d10a4ee9
- [x] Displaying icons in list
- [x] Save icons to database

**Comment by davidchiles** [comment]
@N-Pex Added support for fetching icons. Tried to add it to the `SCRPickFeedsViewController` but the `UIImageView` was always `nil`

**Comment by N-Pex** [comment]
@davidchiles Oh, apparently they were not connected. Checked in a fix. Now you should have a UIImageView connected to the .imageView property.

**Comment by chrisballinger** [comment]
Nice! Every time we tried to connect it in IB it still was nil.
UITableViewCells have a .imageView property built-in, which can cause
problems, so we tried renaming it to something else and hooking it up to
that, but it still was nil.

We'll check out this fix, thanks!

**Comment by chrisballinger** [comment]
Looks like it works! Basic fetching / display added in 601fc806866a89cdf1116f87e7b94ad8897ec105. Right now they aren't saved in the db and are refetched every time.

**Comment by davidchiles** [comment]
The favicon for a feed is fetched and stored in the yap database or on the object in the search view. In the future there should be a more exhaustive search for higher resolution icons.
