### ISSUE TITLE
Missing image for discussion category

### ISSUE THREAD

**Issue by chrisballinger** [guardianproject/securereader_ios#60]
![simulator screen shot sep 9 2015 6 35 43 pm](https://cloud.githubusercontent.com/assets/518687/9778154/a99388b2-5721-11e5-80c6-cd3df0b8b3e2.png)

@cstiens Are we missing an asset here or is this just a bug?

**Comment by cstiens** [comment]
@chrisballinger We are missing an asset! I'll get one created and passed along to you guys.

**Comment by cstiens** [comment]
@chrisballinger The illustration for discussion is on the dev site: https://dev.guardianproject.info/issues/5565

**Comment by cstiens** [comment]
The category illustration for the discussion section of Paik is on the dev
site: https://dev.guardianproject.info/issues/5565

On Wed, Sep 9, 2015 at 8:37 PM, Chris Ballinger notifications@github.com
wrote:

> [image: simulator screen shot sep 9 2015 6 35 43 pm]
> https://cloud.githubusercontent.com/assets/518687/9778154/a99388b2-5721-11e5-80c6-cd3df0b8b3e2.png
> 
> @cstiens https://github.com/cstiens Are we missing an asset here or is
> this just a bug?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/guardianproject/securereader_ios/issues/60.

## 

Carrie Winfrey, Interaction Designer
carriewinfrey.com http://www.carriewinfrey.com  |  @crwinfrey
https://twitter.com/crwinfrey

**Comment by chrisballinger** [comment]
thank you!

**Comment by chrisballinger** [comment]
@N-Pex Can you put these assets in there? Thanks!

**Comment by N-Pex** [comment]
Thanks, fixed now!
