### ISSUE TITLE
Onboarding image categories still rendered at 1x resolution

### ISSUE THREAD

**Issue by chrisballinger** [guardianproject/securereader_ios#61]
@N-Pex Is this a limitation of the SVG library we are using? If so, would it be easier to just use pre-rendered images from Carrie?

![simulator screen shot sep 9 2015 6 35 43 pm](https://cloud.githubusercontent.com/assets/518687/9778154/a99388b2-5721-11e5-80c6-cd3df0b8b3e2.png)

**Comment by N-Pex** [comment]
@chrisballinger I think 2372cc92df4540cb1fec37bb0323d6410ecde70e fixes the problem, could you please try? Thanks.

**Comment by chrisballinger** [comment]
Great! Looks like this is fixed
