### ISSUE TITLE
Remove articles / media past their expiration date

### ISSUE THREAD

**Issue by chrisballinger** [guardianproject/securereader_ios#8]
Purge articles / data that are beyond their expiration. Don't remove items marked as favorites.

We could trigger this method during background fetch operations, and (non-blocking) when the user manually launches the app.

**Comment by davidchiles** [comment]
What is our expiration date? 30 days?

**Comment by N-Pex** [comment]
Added a setting for this in [SCRSettings articleExpiration] now.
